services:
  so-manager-db:
    image: postgres:latest
    container_name: so-manager-db
    environment:
      POSTGRES_USER: esi
      POSTGRES_PASSWORD: esi
      POSTGRES_DB: so
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: