server:
  port: 8081

spring:
  application:
    name: so-manager-address
  datasource:
    url: jdbc:postgresql://localhost:5432/so
    username: esi
    password: esi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

